## Importing necessary libraries

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense
!pip install keras
!pip install tensorflow

Requirement already satisfied: keras in c:\users\silver2\anaconda3\lib\site-packages (2.4.3)
Requirement already satisfied: scipy>=0.14 in c:\users\silver2\anaconda3\lib\site-packages (from keras) (1.6.2)
Requirement already satisfied: pyyaml in c:\users\silver2\anaconda3\lib\site-packages (from keras) (5.4.1)
Requirement already satisfied: h5py in c:\users\silver2\anaconda3\lib\site-packages (from keras) (3.1.0)
Requirement already satisfied: numpy>=1.9.1 in c:\users\silver2\anaconda3\lib\site-packages (from keras) (1.19.5)
Requirement already satisfied: tensorflow in c:\users\silver2\anaconda3\lib\site-packages (2.5.0)
Requirement already satisfied: wheel~=0.35 in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (0.36.2)
Requirement already satisfied: six~=1.15.0 in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (1.15.0)
Requirement already satisfied: protobuf>=3.9.2 in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (3.17.1)
Requirement already satisfied: h5py~=3.1.0 in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (3.1.0)
Requirement already satisfied: astunparse~=1.6.3 in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: numpy~=1.19.2 in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (1.19.5)
Requirement already satisfied: keras-nightly~=2.5.0.dev in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (2.5.0.dev2021032900)
Requirement already satisfied: gast==0.4.0 in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (0.4.0)
Requirement already satisfied: termcolor~=1.1.0 in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (1.1.0)
Requirement already satisfied: tensorboard~=2.5 in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: flatbuffers~=1.12.0 in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (1.12)
Requirement already satisfied: wrapt~=1.12.1 in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (1.12.1)
Requirement already satisfied: opt-einsum~=3.3.0 in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: keras-preprocessing~=1.1.2 in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (1.1.2)
Requirement already satisfied: absl-py~=0.10 in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (0.12.0)
Requirement already satisfied: google-pasta~=0.2 in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: tensorflow-estimator<2.6.0,>=2.5.0rc0 in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: grpcio~=1.34.0 in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (1.34.1)
Requirement already satisfied: typing-extensions~=3.7.4 in c:\users\silver2\anaconda3\lib\site-packages (from tensorflow) (3.7.4.3)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\users\silver2\anaconda3\lib\site-packages (from tensorboard~=2.5->tensorflow) (1.8.0)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in c:\users\silver2\anaconda3\lib\site-packages (from tensorboard~=2.5->tensorflow) (0.6.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\silver2\anaconda3\lib\site-packages (from tensorboard~=2.5->tensorflow) (2.25.1)
Requirement already satisfied: markdown>=2.6.8 in c:\users\silver2\anaconda3\lib\site-packages (from tensorboard~=2.5->tensorflow) (3.3.4)
Requirement already satisfied: google-auth<2,>=1.6.3 in c:\users\silver2\anaconda3\lib\site-packages (from tensorboard~=2.5->tensorflow) (1.30.1)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\silver2\anaconda3\lib\site-packages (from tensorboard~=2.5->tensorflow) (52.0.0.post20210125)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\silver2\anaconda3\lib\site-packages (from tensorboard~=2.5->tensorflow) (1.0.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\silver2\anaconda3\lib\site-packages (from tensorboard~=2.5->tensorflow) (0.4.4)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\users\silver2\anaconda3\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow) (4.2.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\silver2\anaconda3\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\silver2\anaconda3\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow) (4.7.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\silver2\anaconda3\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.5->tensorflow) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\silver2\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow) (0.4.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\silver2\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow) (1.26.4)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\silver2\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\silver2\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\users\silver2\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow) (2.10)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\silver2\anaconda3\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.5->tensorflow) (3.1.0)

#### Getting data

In [24]:
df = pd.read_csv('Dataset used for the main training.csv')
df.head()

,Country name,year,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [25]:
df = df.drop(['Positive affect','Negative affect'],axis = 1)

In [26]:
df = df[df.year == 2020]
df

,Country name,year,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption
24,Albania,2020,9.497,0.710,69.3,0.754,0.007,0.891
51,Argentina,2020,9.850,0.897,69.2,0.823,-0.122,0.816
79,Australia,2020,10.760,0.937,74.2,0.905,0.210,0.491
92,Austria,2020,10.851,0.925,73.6,0.912,0.011,0.464
117,Bahrain,2020,10.620,0.848,69.7,0.945,0.132,NaN
...,...,...,...,...,...,...,...,...
1850,United States,2020,11.001,0.937,68.1,0.850,0.034,0.678
1865,Uruguay,2020,9.937,0.921,69.2,0.908,-0.084,0.491
1893,Venezuela,2020,NaN,0.805,66.9,0.612,NaN,0.811
1933,Zambia,2020,8.117,0.767,56.3,0.750,0.056,0.810
1948,Zimbabwe,2020,7.829,0.717,56.8,0.643,-0.009,0.789

In [27]:
df = df.dropna(axis=0)
df

,Country name,year,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption
24,Albania,2020,9.497,0.710,69.3,0.754,0.007,0.891
51,Argentina,2020,9.850,0.897,69.2,0.823,-0.122,0.816
79,Australia,2020,10.760,0.937,74.2,0.905,0.210,0.491
92,Austria,2020,10.851,0.925,73.6,0.912,0.011,0.464
132,Bangladesh,2020,8.472,0.739,65.3,0.777,-0.009,0.742
...,...,...,...,...,...,...,...,...
1835,United Kingdom,2020,10.626,0.929,72.7,0.885,0.203,0.490
1850,United States,2020,11.001,0.937,68.1,0.850,0.034,0.678
1865,Uruguay,2020,9.937,0.921,69.2,0.908,-0.084,0.491
1933,Zambia,2020,8.117,0.767,56.3,0.750,0.056,0.810
1948,Zimbabwe,2020,7.829,0.717,56.8,0.643,-0.009,0.789

In [28]:
df.describe()

,year,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption
count,81.0,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000
mean,2020.0,9.746025,0.843704,66.977284,0.819370,-0.004704,0.708975
std,0.0,0.948836,0.110200,6.108183,0.094246,0.139524,0.202940
min,2020.0,7.684000,0.507000,50.500000,0.510000,-0.259000,0.164000
25%,2020.0,9.061000,0.767000,64.100000,0.767000,-0.111000,0.609000
50%,2020.0,9.913000,0.887000,68.300000,0.824000,-0.021000,0.784000
75%,2020.0,10.538000,0.936000,72.500000,0.905000,0.091000,0.847000
max,2020.0,11.323000,0.983000,75.200000,0.965000,0.470000,0.961000

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 81 entries, 24 to 1948
Data columns (total 8 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country name                      81 non-null     object
 1   year                              81 non-null     int64
 2   Log GDP per capita                81 non-null     float64
 3   Social support                    81 non-null     float64
 4   Healthy life expectancy at birth  81 non-null     float64
 5   Freedom to make life choices      81 non-null     float64
 6   Generosity                        81 non-null     float64
 7   Perceptions of corruption         81 non-null     float64
dtypes: float64(6), int64(1), object(1)
memory usage: 5.7+ KB

In [30]:
df.describe()

,year,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption
count,81.0,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000
mean,2020.0,9.746025,0.843704,66.977284,0.819370,-0.004704,0.708975
std,0.0,0.948836,0.110200,6.108183,0.094246,0.139524,0.202940
min,2020.0,7.684000,0.507000,50.500000,0.510000,-0.259000,0.164000
25%,2020.0,9.061000,0.767000,64.100000,0.767000,-0.111000,0.609000
50%,2020.0,9.913000,0.887000,68.300000,0.824000,-0.021000,0.784000
75%,2020.0,10.538000,0.936000,72.500000,0.905000,0.091000,0.847000
max,2020.0,11.323000,0.983000,75.200000,0.965000,0.470000,0.961000

### Classifying the countries as happy/not happy

In [31]:
df2 = pd.read_csv('2020 rankings used for classification.csv')
df2.head()

     Country name      Class
0     Albania [+]  Not Happy
1   Argentina [+]      Happy
2   Australia [+]      Happy
3     Austria [+]      Happy
4  Bangladesh [+]  Not Happy

In [32]:
df2['Country name'] = df2['Country name'].str.replace('[+]', '',regex = False)
df2

       Country name      Class
0          Albania   Not Happy
1        Argentina       Happy
2        Australia       Happy
3          Austria       Happy
4       Bangladesh   Not Happy
..              ...        ...
76  United Kingdom       Happy
77   United States       Happy
78         Uruguay       Happy
79          Zambia   Not Happy
80        Zimbabwe   Not Happy

[81 rows x 2 columns]

In [33]:
df2 = df2.dropna()

In [34]:
df = df.reset_index(drop = True)

In [35]:
df['class'] = df2['Class']
df

,Country name,year,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,class
0,Albania,2020,9.497,0.710,69.3,0.754,0.007,0.891,Not Happy
1,Argentina,2020,9.850,0.897,69.2,0.823,-0.122,0.816,Happy
2,Australia,2020,10.760,0.937,74.2,0.905,0.210,0.491,Happy
3,Austria,2020,10.851,0.925,73.6,0.912,0.011,0.464,Happy
4,Bangladesh,2020,8.472,0.739,65.3,0.777,-0.009,0.742,Not Happy
...,...,...,...,...,...,...,...,...,...
76,United Kingdom,2020,10.626,0.929,72.7,0.885,0.203,0.490,Happy
77,United States,2020,11.001,0.937,68.1,0.850,0.034,0.678,Happy
78,Uruguay,2020,9.937,0.921,69.2,0.908,-0.084,0.491,Happy
79,Zambia,2020,8.117,0.767,56.3,0.750,0.056,0.810,Not Happy
80,Zimbabwe,2020,7.829,0.717,56.8,0.643,-0.009,0.789,Not Happy

In [36]:
print(df['class'].value_counts())

label_encode = {"class": {"Happy":0,"Not Happy":1}}

df.replace(label_encode,inplace=True)

print(df['class'].value_counts())

y_values = df['class']

y_values = to_categorical(y_values)

print(y_values)

Happy        53
Not Happy    28
Name: class, dtype: int64
0    53
1    28
Name: class, dtype: int64
[[0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]]

# Using K- Neighbors Classifier

In [37]:
KNN = KNeighborsClassifier()

x = df[['Log GDP per capita',
       'Social support', 'Healthy life expectancy at birth',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption']]
y = df['class']


KNN = KNN.fit(x,y)

test = pd.DataFrame()
test['Log GDP per capita'] = [8.830280304]
test['Social support'] = [0.638051987]
test['Healthy life expectancy at birth'] = [60.09999847]
test['Freedom to make life choices'] = [0.890443385]
test['Generosity'] = [0.071806304]
test['Perceptions of corruption'] =  [0.80526334] 
predict_happiness = KNN.predict(test)

if predict_happiness == [1]:
    print('The country is not happy')
else:
    print('The country is happy')

The country is not happy

# Using neural network

## Standardising the data

In [44]:
x_values = df[['Log GDP per capita',
       'Social support', 'Healthy life expectancy at birth',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption']]
print(x_values.head())
standardise = StandardScaler()

x_values = standardise.fit_transform(x_values)
x_values_df = pd.DataFrame(x_values)

   Log GDP per capita  Social support  Healthy life expectancy at birth  \
0               9.497           0.710                              69.3
1               9.850           0.897                              69.2
2              10.760           0.937                              74.2
3              10.851           0.925                              73.6
4               8.472           0.739                              65.3

   Freedom to make life choices  Generosity  Perceptions of corruption
0                         0.754       0.007                      0.891
1                         0.823      -0.122                      0.816
2                         0.905       0.210                      0.491
3                         0.912       0.011                      0.464
4                         0.777      -0.009                      0.742

In [45]:
print(x_values_df.head())

          0         1         2         3         4         5
0 -0.264088 -1.220839  0.382632 -0.697936  0.084406  0.902528
1  0.110265  0.486645  0.366159  0.038752 -0.845929  0.530658
2  1.075310  0.851882  1.189833  0.914237  1.548422 -1.080782
3  1.171815  0.742311  1.090992  0.988973  0.113254 -1.214655
4 -1.351090 -0.956042 -0.276307 -0.452373 -0.030984  0.163746

In [46]:
print(x_values_df.describe())

                  0             1             2             3             4  \
count  8.100000e+01  8.100000e+01  8.100000e+01  8.100000e+01  8.100000e+01
mean   1.288407e-15 -2.686466e-16 -1.255511e-15 -4.906912e-16  1.661908e-17
std    1.006231e+00  1.006231e+00  1.006231e+00  1.006231e+00  1.006231e+00
min   -2.186755e+00 -3.074419e+00 -2.714383e+00 -3.303036e+00 -1.833960e+00
25%   -7.264614e-01 -7.003763e-01 -4.739889e-01 -5.591395e-01 -7.665985e-01
50%    1.770755e-01  3.953355e-01  2.178974e-01  4.942888e-02 -1.175273e-01
75%    8.398814e-01  8.427512e-01  9.097838e-01  9.142366e-01  6.902058e-01
max    1.672365e+00  1.271905e+00  1.354568e+00  1.554835e+00  3.423517e+00

                  5
count  8.100000e+01
mean  -6.250144e-16
std    1.006231e+00
min   -2.702138e+00
25%   -4.957051e-01
50%    3.719931e-01
75%    6.843644e-01
max    1.249608e+00

## Making the model

In [47]:
model = Sequential()

model.add(Dense(6,input_dim=6,activation='relu'))


model.add(Dense(6,activation='relu'))
model.add(Dense(6,activation='relu'))
model.add(Dense(2,activation='softmax'))

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [48]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 6)                 42
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 42
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 42
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 14
=================================================================
Total params: 140
Trainable params: 140
Non-trainable params: 0
_________________________________________________________________

### Encoding

In [49]:
print(df['class'].value_counts())

label_encode = {"class": {"Happy":0, "Not Happy":1}}

df.replace(label_encode,inplace=True)

print(df['class'].value_counts())

y_values = df['class']

y_values = to_categorical(y_values)

print(y_values)

0    53
1    28
Name: class, dtype: int64
0    53
1    28
Name: class, dtype: int64
[[0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]]

## Training the neural network

In [50]:
model.fit(x_values,y_values,epochs=20,shuffle=True)

Epoch 1/20
3/3 [==============================] - 15s 6ms/step - loss: 0.7360 - accuracy: 0.5506
Epoch 2/20
3/3 [==============================] - 0s 2ms/step - loss: 0.7289 - accuracy: 0.5753
Epoch 3/20
3/3 [==============================] - 0s 2ms/step - loss: 0.7300 - accuracy: 0.5932
Epoch 4/20
3/3 [==============================] - 0s 4ms/step - loss: 0.7199 - accuracy: 0.5753
Epoch 5/20
3/3 [==============================] - 0s 4ms/step - loss: 0.7077 - accuracy: 0.6049
Epoch 6/20
3/3 [==============================] - 0s 6ms/step - loss: 0.7068 - accuracy: 0.6189
Epoch 7/20
3/3 [==============================] - 0s 3ms/step - loss: 0.6953 - accuracy: 0.6228
Epoch 8/20
3/3 [==============================] - 0s 3ms/step - loss: 0.6953 - accuracy: 0.5954
Epoch 9/20
3/3 [==============================] - 0s 4ms/step - loss: 0.6940 - accuracy: 0.6117
Epoch 10/20
3/3 [==============================] - 0s 5ms/step - loss: 0.6858 - accuracy: 0.6475
Epoch 11/20
3/3 [==============================] - 0s 6ms/step - loss: 0.6783 - accuracy: 0.6793
Epoch 12/20
3/3 [==============================] - 0s 5ms/step - loss: 0.6743 - accuracy: 0.7213
Epoch 13/20
3/3 [==============================] - 0s 3ms/step - loss: 0.6713 - accuracy: 0.7197
Epoch 14/20
3/3 [==============================] - 0s 6ms/step - loss: 0.6636 - accuracy: 0.7789
Epoch 15/20
3/3 [==============================] - 0s 2ms/step - loss: 0.6638 - accuracy: 0.7460
Epoch 16/20
3/3 [==============================] - 0s 4ms/step - loss: 0.6560 - accuracy: 0.7935
Epoch 17/20
3/3 [==============================] - 0s 6ms/step - loss: 0.6542 - accuracy: 0.7880
Epoch 18/20
3/3 [==============================] - 0s 3ms/step - loss: 0.6496 - accuracy: 0.7980
Epoch 19/20
3/3 [==============================] - 0s 2ms/step - loss: 0.6334 - accuracy: 0.8472
Epoch 20/20
3/3 [==============================] - 0s 6ms/step - loss: 0.6316 - accuracy: 0.8276

In [51]:
from sklearn.model_selection import train_test_split

x_values = df[['Log GDP per capita',
       'Social support', 'Healthy life expectancy at birth',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption']]

x_train, x_test, y_train, y_test = train_test_split(x_values,y_values,test_size=0.25,random_state=10)
print("Number of rows in x_train:", x_train.shape[0])
print("Number of rows in x_test:", x_test.shape[0])
print("Number of rows in y_train:", y_train.shape[0])
print("Number of rows in y_test:", y_test.shape[0])
standardise = StandardScaler()
x_train = standardise.fit_transform(x_train)
x_test = standardise.transform(x_test)

Number of rows in x_train: 60
Number of rows in x_test: 21
Number of rows in y_train: 60
Number of rows in y_test: 21

In [52]:
model_val = Sequential()
model_val.add(Dense(6,input_dim=6,activation='relu'))
model_val.add(Dense(6,activation='relu'))
model_val.add(Dense(2,activation='softmax'))
model_val.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model_val.fit(x_values,y_values,epochs=50,shuffle=True)

Epoch 1/50
3/3 [==============================] - 1s 998us/step - loss: 2.0171 - accuracy: 0.6318
Epoch 2/50
3/3 [==============================] - 0s 3ms/step - loss: 1.6014 - accuracy: 0.6865
Epoch 3/50
3/3 [==============================] - 0s 2ms/step - loss: 1.7662 - accuracy: 0.6279
Epoch 4/50
3/3 [==============================] - 0s 3ms/step - loss: 1.3539 - accuracy: 0.6865
Epoch 5/50
3/3 [==============================] - 0s 5ms/step - loss: 1.2647 - accuracy: 0.6865
Epoch 6/50
3/3 [==============================] - 0s 4ms/step - loss: 1.2249 - accuracy: 0.6709
Epoch 7/50
3/3 [==============================] - 0s 6ms/step - loss: 1.1167 - accuracy: 0.6709
Epoch 8/50
3/3 [==============================] - 0s 4ms/step - loss: 1.0584 - accuracy: 0.6592
Epoch 9/50
3/3 [==============================] - 0s 4ms/step - loss: 0.9326 - accuracy: 0.6670
Epoch 10/50
3/3 [==============================] - 0s 2ms/step - loss: 0.8289 - accuracy: 0.6748
Epoch 11/50
3/3 [==============================] - 0s 7ms/step - loss: 0.8031 - accuracy: 0.6553
Epoch 12/50
3/3 [==============================] - 0s 4ms/step - loss: 0.7768 - accuracy: 0.6397
Epoch 13/50
3/3 [==============================] - 0s 6ms/step - loss: 0.6610 - accuracy: 0.6748
Epoch 14/50
3/3 [==============================] - 0s 5ms/step - loss: 0.6498 - accuracy: 0.6592
Epoch 15/50
3/3 [==============================] - 0s 4ms/step - loss: 0.6040 - accuracy: 0.6787
Epoch 16/50
3/3 [==============================] - 0s 3ms/step - loss: 0.6406 - accuracy: 0.6358
Epoch 17/50
3/3 [==============================] - 0s 6ms/step - loss: 0.6578 - accuracy: 0.6045
Epoch 18/50
3/3 [==============================] - 0s 4ms/step - loss: 0.6141 - accuracy: 0.6553
Epoch 19/50
3/3 [==============================] - 0s 5ms/step - loss: 0.6197 - accuracy: 0.6514
Epoch 20/50
3/3 [==============================] - 0s 2ms/step - loss: 0.6209 - accuracy: 0.6475
Epoch 21/50
3/3 [==============================] - 0s 3ms/step - loss: 0.6227 - accuracy: 0.6514
Epoch 22/50
3/3 [==============================] - 0s 6ms/step - loss: 0.6294 - accuracy: 0.6358
Epoch 23/50
3/3 [==============================] - 0s 5ms/step - loss: 0.6053 - accuracy: 0.6748
Epoch 24/50
3/3 [==============================] - 0s 3ms/step - loss: 0.6347 - accuracy: 0.6240
Epoch 25/50
3/3 [==============================] - 0s 3ms/step - loss: 0.6180 - accuracy: 0.6475
Epoch 26/50
3/3 [==============================] - 0s 6ms/step - loss: 0.6122 - accuracy: 0.6553
Epoch 27/50
3/3 [==============================] - 0s 5ms/step - loss: 0.6224 - accuracy: 0.6475
Epoch 28/50
3/3 [==============================] - 0s 3ms/step - loss: 0.6273 - accuracy: 0.6358
Epoch 29/50
3/3 [==============================] - 0s 4ms/step - loss: 0.6083 - accuracy: 0.6631
Epoch 30/50
3/3 [==============================] - 0s 5ms/step - loss: 0.5825 - accuracy: 0.6983
Epoch 31/50
3/3 [==============================] - 0s 5ms/step - loss: 0.5820 - accuracy: 0.6943
Epoch 32/50
3/3 [==============================] - 0s 3ms/step - loss: 0.5987 - accuracy: 0.6748
Epoch 33/50
3/3 [==============================] - 0s 4ms/step - loss: 0.6247 - accuracy: 0.6397
Epoch 34/50
3/3 [==============================] - 0s 3ms/step - loss: 0.6055 - accuracy: 0.6631
Epoch 35/50
3/3 [==============================] - 0s 5ms/step - loss: 0.6222 - accuracy: 0.6436
Epoch 36/50
3/3 [==============================] - 0s 5ms/step - loss: 0.6056 - accuracy: 0.6670
Epoch 37/50
3/3 [==============================] - 0s 3ms/step - loss: 0.6074 - accuracy: 0.6592
Epoch 38/50
3/3 [==============================] - 0s 3ms/step - loss: 0.5999 - accuracy: 0.6709
Epoch 39/50
3/3 [==============================] - 0s 3ms/step - loss: 0.5992 - accuracy: 0.6748
Epoch 40/50
3/3 [==============================] - 0s 5ms/step - loss: 0.6058 - accuracy: 0.6631
Epoch 41/50
3/3 [==============================] - 0s 2ms/step - loss: 0.5942 - accuracy: 0.6787
Epoch 42/50
3/3 [==============================] - 0s 5ms/step - loss: 0.6303 - accuracy: 0.6240
Epoch 43/50
3/3 [==============================] - 0s 2ms/step - loss: 0.6062 - accuracy: 0.6631
Epoch 44/50
3/3 [==============================] - 0s 5ms/step - loss: 0.6032 - accuracy: 0.6631
Epoch 45/50
3/3 [==============================] - 0s 4ms/step - loss: 0.6192 - accuracy: 0.6436
Epoch 46/50
3/3 [==============================] - 0s 3ms/step - loss: 0.6076 - accuracy: 0.6592
Epoch 47/50
3/3 [==============================] - 0s 3ms/step - loss: 0.6199 - accuracy: 0.6436
Epoch 48/50
3/3 [==============================] - 0s 3ms/step - loss: 0.6081 - accuracy: 0.6592
Epoch 49/50
3/3 [==============================] - 0s 5ms/step - loss: 0.5957 - accuracy: 0.6748
Epoch 50/50
3/3 [==============================] - 0s 3ms/step - loss: 0.6267 - accuracy: 0.6318

In [53]:
model_val.fit(x_train,y_train,epochs=50,shuffle=True,validation_data=(x_test,y_test))

Epoch 1/50
2/2 [==============================] - 1s 569ms/step - loss: 0.6646 - accuracy: 0.6333 - val_loss: 0.6926 - val_accuracy: 0.6190
Epoch 2/50
2/2 [==============================] - 0s 27ms/step - loss: 0.6630 - accuracy: 0.6333 - val_loss: 0.6914 - val_accuracy: 0.5714
Epoch 3/50
2/2 [==============================] - 0s 49ms/step - loss: 0.6604 - accuracy: 0.6333 - val_loss: 0.6899 - val_accuracy: 0.5714
Epoch 4/50
2/2 [==============================] - 0s 50ms/step - loss: 0.6575 - accuracy: 0.6500 - val_loss: 0.6881 - val_accuracy: 0.5714
Epoch 5/50
2/2 [==============================] - 0s 41ms/step - loss: 0.6545 - accuracy: 0.6667 - val_loss: 0.6862 - val_accuracy: 0.5714
Epoch 6/50
2/2 [==============================] - 0s 34ms/step - loss: 0.6514 - accuracy: 0.6667 - val_loss: 0.6842 - val_accuracy: 0.5714
Epoch 7/50
2/2 [==============================] - 0s 52ms/step - loss: 0.6479 - accuracy: 0.6667 - val_loss: 0.6822 - val_accuracy: 0.5714
Epoch 8/50
2/2 [==============================] - 0s 54ms/step - loss: 0.6444 - accuracy: 0.6833 - val_loss: 0.6801 - val_accuracy: 0.5238
Epoch 9/50
2/2 [==============================] - 0s 46ms/step - loss: 0.6412 - accuracy: 0.7000 - val_loss: 0.6777 - val_accuracy: 0.4762
Epoch 10/50
2/2 [==============================] - 0s 48ms/step - loss: 0.6374 - accuracy: 0.7333 - val_loss: 0.6749 - val_accuracy: 0.4762
Epoch 11/50
2/2 [==============================] - 0s 68ms/step - loss: 0.6337 - accuracy: 0.7333 - val_loss: 0.6719 - val_accuracy: 0.5238
Epoch 12/50
2/2 [==============================] - 0s 55ms/step - loss: 0.6301 - accuracy: 0.7500 - val_loss: 0.6686 - val_accuracy: 0.5238
Epoch 13/50
2/2 [==============================] - 0s 63ms/step - loss: 0.6257 - accuracy: 0.7333 - val_loss: 0.6652 - val_accuracy: 0.5238
Epoch 14/50
2/2 [==============================] - 0s 48ms/step - loss: 0.6218 - accuracy: 0.7500 - val_loss: 0.6612 - val_accuracy: 0.5238
Epoch 15/50
2/2 [==============================] - 0s 48ms/step - loss: 0.6171 - accuracy: 0.8000 - val_loss: 0.6572 - val_accuracy: 0.5714
Epoch 16/50
2/2 [==============================] - 0s 68ms/step - loss: 0.6127 - accuracy: 0.7833 - val_loss: 0.6532 - val_accuracy: 0.5714
Epoch 17/50
2/2 [==============================] - 0s 58ms/step - loss: 0.6085 - accuracy: 0.8167 - val_loss: 0.6488 - val_accuracy: 0.6190
Epoch 18/50
2/2 [==============================] - 0s 58ms/step - loss: 0.6040 - accuracy: 0.8167 - val_loss: 0.6443 - val_accuracy: 0.6190
Epoch 19/50
2/2 [==============================] - 0s 45ms/step - loss: 0.5994 - accuracy: 0.8333 - val_loss: 0.6398 - val_accuracy: 0.6190
Epoch 20/50
2/2 [==============================] - 0s 27ms/step - loss: 0.5947 - accuracy: 0.8667 - val_loss: 0.6349 - val_accuracy: 0.6190
Epoch 21/50
2/2 [==============================] - 0s 62ms/step - loss: 0.5896 - accuracy: 0.8833 - val_loss: 0.6296 - val_accuracy: 0.6190
Epoch 22/50
2/2 [==============================] - 0s 67ms/step - loss: 0.5845 - accuracy: 0.8833 - val_loss: 0.6239 - val_accuracy: 0.6190
Epoch 23/50
2/2 [==============================] - 0s 50ms/step - loss: 0.5792 - accuracy: 0.8833 - val_loss: 0.6180 - val_accuracy: 0.6667
Epoch 24/50
2/2 [==============================] - 0s 34ms/step - loss: 0.5732 - accuracy: 0.8667 - val_loss: 0.6119 - val_accuracy: 0.6667
Epoch 25/50
2/2 [==============================] - 0s 34ms/step - loss: 0.5675 - accuracy: 0.8667 - val_loss: 0.6057 - val_accuracy: 0.6667
Epoch 26/50
2/2 [==============================] - 0s 22ms/step - loss: 0.5614 - accuracy: 0.8500 - val_loss: 0.5995 - val_accuracy: 0.7143
Epoch 27/50
2/2 [==============================] - 0s 37ms/step - loss: 0.5550 - accuracy: 0.8500 - val_loss: 0.5930 - val_accuracy: 0.7143
Epoch 28/50
2/2 [==============================] - 0s 49ms/step - loss: 0.5494 - accuracy: 0.8667 - val_loss: 0.5861 - val_accuracy: 0.7143
Epoch 29/50
2/2 [==============================] - 0s 38ms/step - loss: 0.5424 - accuracy: 0.8667 - val_loss: 0.5795 - val_accuracy: 0.7143
Epoch 30/50
2/2 [==============================] - 0s 44ms/step - loss: 0.5363 - accuracy: 0.8667 - val_loss: 0.5726 - val_accuracy: 0.7619
Epoch 31/50
2/2 [==============================] - 0s 49ms/step - loss: 0.5291 - accuracy: 0.8667 - val_loss: 0.5656 - val_accuracy: 0.7619
Epoch 32/50
2/2 [==============================] - 0s 57ms/step - loss: 0.5222 - accuracy: 0.8667 - val_loss: 0.5584 - val_accuracy: 0.7619
Epoch 33/50
2/2 [==============================] - 0s 57ms/step - loss: 0.5149 - accuracy: 0.8667 - val_loss: 0.5506 - val_accuracy: 0.7619
Epoch 34/50
2/2 [==============================] - 0s 58ms/step - loss: 0.5063 - accuracy: 0.8667 - val_loss: 0.5425 - val_accuracy: 0.7619
Epoch 35/50
2/2 [==============================] - 0s 47ms/step - loss: 0.4974 - accuracy: 0.8667 - val_loss: 0.5343 - val_accuracy: 0.7619
Epoch 36/50
2/2 [==============================] - 0s 40ms/step - loss: 0.4887 - accuracy: 0.8667 - val_loss: 0.5257 - val_accuracy: 0.7619
Epoch 37/50
2/2 [==============================] - 0s 39ms/step - loss: 0.4791 - accuracy: 0.8667 - val_loss: 0.5169 - val_accuracy: 0.7619
Epoch 38/50
2/2 [==============================] - 0s 50ms/step - loss: 0.4685 - accuracy: 0.8667 - val_loss: 0.5080 - val_accuracy: 0.7619
Epoch 39/50
2/2 [==============================] - 0s 68ms/step - loss: 0.4587 - accuracy: 0.8667 - val_loss: 0.4992 - val_accuracy: 0.7619
Epoch 40/50
2/2 [==============================] - 0s 68ms/step - loss: 0.4469 - accuracy: 0.8667 - val_loss: 0.4907 - val_accuracy: 0.7619
Epoch 41/50
2/2 [==============================] - 0s 24ms/step - loss: 0.4376 - accuracy: 0.8667 - val_loss: 0.4822 - val_accuracy: 0.7619
Epoch 42/50
2/2 [==============================] - 0s 35ms/step - loss: 0.4261 - accuracy: 0.8667 - val_loss: 0.4740 - val_accuracy: 0.7619
Epoch 43/50
2/2 [==============================] - 0s 20ms/step - loss: 0.4166 - accuracy: 0.8667 - val_loss: 0.4660 - val_accuracy: 0.7619
Epoch 44/50
2/2 [==============================] - 0s 19ms/step - loss: 0.4063 - accuracy: 0.8667 - val_loss: 0.4584 - val_accuracy: 0.7619
Epoch 45/50
2/2 [==============================] - 0s 27ms/step - loss: 0.3964 - accuracy: 0.8667 - val_loss: 0.4509 - val_accuracy: 0.7619
Epoch 46/50
2/2 [==============================] - 0s 50ms/step - loss: 0.3872 - accuracy: 0.8667 - val_loss: 0.4435 - val_accuracy: 0.7619
Epoch 47/50
2/2 [==============================] - 0s 54ms/step - loss: 0.3784 - accuracy: 0.8667 - val_loss: 0.4363 - val_accuracy: 0.7619
Epoch 48/50
2/2 [==============================] - 0s 61ms/step - loss: 0.3704 - accuracy: 0.8667 - val_loss: 0.4293 - val_accuracy: 0.7619
Epoch 49/50
2/2 [==============================] - 0s 47ms/step - loss: 0.3620 - accuracy: 0.8667 - val_loss: 0.4224 - val_accuracy: 0.7619
Epoch 50/50
2/2 [==============================] - 0s 20ms/step - loss: 0.3537 - accuracy: 0.8667 - val_loss: 0.4158 - val_accuracy: 0.8095

## Testing the model with extra data

In [54]:
df3 = pd.read_csv('Extra data for testing.csv')
df3

,Country name,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption
0,India,8.830280,0.638052,60.099998,0.890443,0.071806,0.805263
1,United States,10.922465,0.903856,68.300003,0.824607,0.107713,0.709928
2,Pakistan,8.561664,0.685059,58.500000,0.772569,0.053522,0.798842
3,Philippines,8.985703,0.845803,61.900002,0.917808,-0.113129,0.726483
4,Russia,10.132390,0.908726,64.300003,0.729282,-0.156226,0.865312
5,Italy,10.480516,0.912656,73.599998,0.650009,-0.023462,0.887825
6,Japan,10.581618,0.886432,75.000000,0.773472,-0.272972,0.686785
7,Mexico,9.769919,0.858069,68.300003,0.816200,-0.181818,0.808638
8,Afghanistan,7.494588,0.507516,52.599998,0.373536,-0.084888,0.927606
9,Bangladesh,8.220746,0.705556,64.300003,0.901471,-0.038008,0.701421

In [55]:
x_new = df3[['Log GDP per capita','Social support','Healthy life expectancy at birth','Freedom to make life choices','Generosity','Perceptions of corruption']]
x_new_scale = standardise.transform(x_new)
y_new = model_val.predict(x_new_scale)

In [56]:
print(y_new)

[[0.4374887  0.5625113 ]
 [0.8174185  0.18258148]
 [0.3991704  0.60082954]
 [0.82809573 0.17190433]
 [0.53364664 0.46635333]
 [0.7254338  0.27456608]
 [0.8175341  0.18246591]
 [0.7731347  0.22686534]
 [0.3303534  0.6696466 ]
 [0.6091862  0.3908139 ]]

In [57]:
classes = []
for ii in range(0,y_new.shape[0]):
    classes.append(np.argmax(y_new[ii,:]))
print(classes)

[1, 0, 1, 0, 0, 0, 0, 0, 1, 0]

## Deployment(only KNN)

In [43]:
cntry = input('Enter the name of the country: ')
LGPC = float(input("Enter the Log GDP per capita: "))
SS = float(input('Enter the social support: '))
HLEAB = float(input('Enter the healthy life expectancy at birth: '))
FTMLC = float(input('Enter the freedom to make life choices: '))
G = float(input('Enter the generosity: '))
POC = float(input('Enter the perceptions of corruption: '))

KNN = KNeighborsClassifier()

x = df[['Log GDP per capita',
       'Social support', 'Healthy life expectancy at birth',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption']]
y = df['class']


KNN = KNN.fit(x,y)

test = pd.DataFrame()
test['Log GDP per capita'] = [LGPC]
test['Social support'] = [SS]
test['Healthy life expectancy at birth'] = [HLEAB]
test['Freedom to make life choices'] = [FTMLC]
test['Generosity'] = [G]
test['Perceptions of corruption'] =  [POC] 
predict_happiness = KNN.predict(test)

if predict_happiness == [1]:
    print(cntry + ' ' + 'is not happy')
else:
    print(cntry + ' ' + 'is happy')

Enter the name of the country: India
Enter the Log GDP per capita: 10.9
Enter the social support: 0.9
Enter the healthy life expectancy at birth: 68.3
Enter the freedom to make life choices: 0.8
Enter the generosity: 0.1
Enter the perceptions of corruption: 0.7
India is happy

# That's it, Thank you Intel and CBSE for this great oppurtunity!